language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"

install:
    - python setup.py install
    - pip install -r requirements_test.txt

script:
    - pep8 --ignore=E501 sensu_plugin
    - pylint --rcfile=pylint.rc sensu_plugin
    - nosetests sensu_plugin/test/
